kind: pipeline
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
- name: publish
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet publish
  
trigger:
  branch:
  - main
  - feature/*
  event:
  - push
  - pull_request
