kind: pipeline
name: default

steps:
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
  when:
      event:
        include:
          - push
      branch:
        include:
          - main